import { Logger } from '@nestjs/common';

/**
 * On-demand ISR revalidation bridge.
 *
 * Storefront pages are statically regenerated by Next with `next.tags`;
 * after an admin write (review/product/LP change) the backend POSTs the
 * affected tags to the frontend's `/api/internal/revalidate` route handler
 * so shoppers see the change on the NEXT request instead of waiting for the
 * time-based revalidate window.
 *
 * Best-effort by contract: a cache refresh failure must never fail or delay
 * the admin mutation, so every error is swallowed (logged at warn level).
 * When REVALIDATE_URL/REVALIDATE_SECRET are unset (local dev without the
 * link configured) the call is a no-op.
 */

// Keep these in sync with frontend/src/lib/cache-tags.ts.
export const CACHE_TAGS = {
  // All public catalog content: PDPs, LP pages, home, collections, search…
  STOREFRONT: 'storefront',
} as const;

const logger = new Logger('Revalidation');

export async function revalidateCache(tags: string[]): Promise<void> {
  const url = process.env.REVALIDATE_URL?.trim();
  const secret = process.env.REVALIDATE_SECRET?.trim();
  if (!url || !secret || tags.length === 0) return;

  const endpoint = `${url.replace(/\/+$/, '')}/api/internal/revalidate`;
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 2500);
    try {
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'x-revalidate-secret': secret,
        },
        body: JSON.stringify({ tags }),
        signal: controller.signal,
      });
      if (!res.ok) {
        logger.warn(`revalidate ${tags.join(',')} -> HTTP ${res.status}`);
      }
    } finally {
      clearTimeout(timer);
    }
  } catch (error) {
    logger.warn(`revalidate ${tags.join(',')} failed: ${(error as Error).message}`);
  }
}
