/**
 * Philippine ZIP code lookup for the checkout address cascade (province →
 * city → barangay → postal code).
 *
 * Data: `src/data/psgc/postal-codes.json`, generated by
 * `scripts/build-postal-codes.mjs` from use-postal-ph —
 * https://github.com/blckclov3r/use-postal-ph (MIT, © 2024 blckclov3r);
 * see LICENSE-postal-codes. Keys are the exact PSGC province/city names the
 * form already holds, so no name normalization is needed to find a city.
 *
 * Outside Metro Manila a city/municipality has exactly ONE ZIP → auto-fill.
 * Inside Metro Manila the ZIP varies by area/barangay, so the selected
 * barangay is matched and, failing that, the city's ZIPs are offered as
 * choices. We never guess: an address we cannot resolve returns no ZIP rather
 * than a plausible-looking wrong one, because a wrong ZIP delays a delivery.
 */
import postalJson from "@/data/psgc/postal-codes.json";

/** [displayLabel (Metro Manila only), normalizedAreaKey, zip] */
type PostalEntry = [string, string, string];

// JSON imports widen tuples to string[][]; the generator guarantees triples.
const CITIES = postalJson.cities as unknown as Record<string, PostalEntry[]>;

/**
 * Must stay identical to `normKey()` in scripts/build-postal-codes.mjs — the
 * area keys stored in the JSON were produced with it, so a drift here silently
 * costs matches (never wrong matches, since we compare for equality only).
 */
export function postalKey(value: string): string {
  return String(value ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/\(.*?\)/g, " ")
    .replace(/\bsta\.?\b/g, "santa")
    .replace(/\bsto\.?\b/g, "santo")
    .replace(/\bgen\.?\b/g, "general")
    .replace(/\binc\.?\b/g, " ")
    .replace(
      /\b(city|province|municipality|capital|village|subd|subdivision|proper|the|of)\b/g,
      " ",
    )
    .replace(/[^a-z0-9]/g, "")
    .trim();
}

export interface PostalLookup {
  /** ZIP to prefill, or null when the address does not determine one. */
  auto: string | null;
  /** Area choices to offer when more than one ZIP applies (empty otherwise). */
  options: { label: string; zip: string }[];
}

export function lookupPostalCode(
  province: string,
  city: string,
  barangay = "",
): PostalLookup {
  const entries = CITIES[`${province}|${city}`];
  if (!entries || entries.length === 0) return { auto: null, options: [] };

  // Collapse areas that share a ZIP (e.g. most of Pasig is 1600) so the
  // dropdown lists postcodes, not 33 near-duplicate rows.
  const options: { label: string; zip: string }[] = [];
  const seen = new Set<string>();
  for (const [label, , zip] of entries) {
    if (seen.has(zip)) continue;
    seen.add(zip);
    options.push({ label, zip });
  }

  // One postcode for the whole city — nothing to choose.
  if (options.length === 1) return { auto: options[0].zip, options: [] };

  const key = postalKey(barangay);
  if (key) {
    const hits = entries.filter(([, areaKey]) => areaKey === key);
    // Exactly one area is unambiguous. Two different areas collapsing onto the
    // same normalized name (the normalizer drops words like "proper") would
    // make the pick arbitrary — offer the dropdown instead of guessing.
    if (hits.length === 1) return { auto: hits[0][2], options };
  }
  return { auto: null, options };
}
